### PR TITLE
Make text and pattern const strings

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**

### CODE REVIEW

**Comment by RagnarGrootKoerkamp** [comment]
Oh huh; I always thought that `cigar()` returns a string of `MID`, without `X`, but it seems that that is not true (anymore). Is this function still useful at all in that case?

**Review by smarco — APPROVED** [review]

**Comment by smarco** [comment]
It seems that the CIGAR can contain X. This function is useful for retrieving mismatches and comparing alignments. Nothing else is remarkable about this function.

Let me know

**Comment by RagnarGrootKoerkamp** [comment]
So my understanding of Cigar is:
- `X`: mismatch
- `=`: match
- `M`: either match or mismatch (but possibly also used for match only sometimes?)

I always assumed the `M` returned by WFA meant `match or mismatch`. Then I found this function `cigar_add_mismatches` which 'confirmed' my assumption, in that it explicitly separates `M` into `M` and `X`s.

So I tried to call that function on WFA output, but then it crashed because apparently the output already contains `X` symbols, and the function isn't even needed. So now I'm wondering if `cigar_add_matches` should just be deleted since WFA does not (ever?) generate output on which it is useful.

**Comment by RagnarGrootKoerkamp** [comment]
It would be nice to explicitly document the structure of the cigar returned by WFA:
- a string of `MXID` characters only
- `M` is match, `X` is mismatch (I'd appreciate replacing `M` by `=`, but maybe don't for backwards compatibility.)
- No counts are included (ie no `10MX10M2I5M...`)

**Comment by smarco** [comment]
To clarify, WFAlib has always explicitly differentiated between matches 'M' and mismatches 'X' (motivated by simplicity).

However, [SAM specification](https://samtools.github.io/hts-specs/SAMv1.pdf) states in Section 1.4 (point 6) that CIGAR op 'M' is an alignment match (can be a sequence match or mismatch). Therefore, libraries like KSW2 and Gaba return CIGARs that don't discriminate between matches and mismatches. 

In the `benchmark` branch, this function has been renamed to `cigar_discover_mismatches()` (as in the `development` branch), and it is used to process the results from KSW2 and Gaba within the benchmarking tool `./bin/align_benchmark`.

Regarding the documentation, yes, you are right. We can elaborate on the structure of the cigar returned by WFA by (1) a PR with the content or (2) opening a ticket so I can address it with the next merge of the `dev` branch with the `main` (to happen very soon).

Let me know and thanks for the feedback.

**Pull request merged**
